apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-helloworld-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: helloworld
          image: rajmanohar21/helloworld