apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: pythonapp
          image: sheshuvalandas/pythonapp:latest
          ports:
          - containerPort: 5001